### ISSUE TITLE
Failed to activate the atom-pair package

### ISSUE THREAD

**Issue by LichtHund** [pusher/atom-pair#129] opened 2017-08-17 20:50 UTC
I just installed Atom Pair and this popped up, anyone knows what could be the problem?

`SyntaxError: Unexpected token )
    at Module.get_Module._compile (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:94:52)
    at Object.value [as .js] (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/atom-pair/lib/modules/session.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/atom-pair/lib/modules/session.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/atom-pair/lib/modules/session.coffee:1:1)
    at Module.get_Module._compile (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .coffee] (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
    at Object.activate (file:///C:/Users/Matt/.atom/packages/atom-pair/lib/atom_pair.coffee:42:15)
    at Package.module.exports.Package.activateNow (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:253:25)
    at C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:99:21)
    at C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:645:40)
    at C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\node_modules\settings-view\lib\package-manager.js:535:35
    at exit (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\Matt\AppData\Local\atom\app-1.19.2\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`

Cheers.

**Comment by oumad** [comment] 2017-08-18 10:32
Duplicate of #126

**Closed as completed** 2017-08-30 09:55 UTC
