### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by despairblue** [pusher/atom-pair#22] opened 2015-03-12 09:46 UTC
[Enter steps to reproduce below:]
1. choose `Set Configuration Keys` from command palette

**Atom Version**: 0.187.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v0.37.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/despairblue/.atom/packages/atom-pair/lib/atom_pair.coffee:51

TypeError: undefined is not a function
  at atom-workspace.subscriptions.add.atom.commands.add.AtomPair:set configuration keys (/home/despairblue/.atom/packages/atom-pair/lib/atom_pair.coffee:51:99)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -1:03.0 command-palette:toggle (atom-text-editor.editor)
     -1:02.0 core:confirm (atom-text-editor.editor.mini)
     -1:02.0 AtomPair:set configuration keys (atom-text-editor.editor)
     -1:00.2 command-palette:toggle (atom-text-editor.editor)
     -0:54.7 core:move-down (atom-text-editor.editor.mini)
     -0:53.7 core:confirm (atom-text-editor.editor.mini)
     -0:53.7 application:open-your-config (atom-text-editor.editor)
     -0:07.6 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.1 core:backspace (atom-text-editor.editor.mini)
  4x -0:02.9 core:move-down (atom-text-editor.editor.mini)
     -0:01.2 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 AtomPair:set configuration keys (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "linter-scspell",
      "navigate",
      "atom-ternjs"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "atom-pair": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atom-pair, v0.37.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
block-cursor, v0.9.8
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.4.4
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.5.1
filetype-color, v0.1.4
git-log, v0.3.0
go-plus, v3.3.0
grammar-token-limit, v0.1.1
highlight-selected, v0.9.1
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
language-dockerfile, v0.1.0
language-fish-shell, v1.0.1
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.2
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-eslint, v0.4.2
linter-htmlhint, v0.0.8
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.0
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
open-last-project, v0.3.4
package-cop, v0.2.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
symbols-tree-view, v0.6.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.28.0
zentabs, v0.8.2

# Dev
autocomplete-plus, v2.0.2
```

**Comment by snollygolly** [comment] 2015-03-12 12:34
Looks like it's calling a function when you select "set configuration keys" that doesn't exist:

`@subscriptions.add atom.commands.add 'atom-workspace', 'AtomPair:set configuration keys': => @setConfig()`

What is `setConfig` supposed to do?

Also, this is a duplicate of: https://github.com/pusher/atom-pair/issues/19

**Comment by jpatel531** [comment] 2015-03-12 23:13
^ this should solve this. This subscription was no longer needed after allowing users to set configs via the package settings. Same goes for issue #19

**Closed as completed** 2015-03-12 23:14 UTC
