### ISSUE TITLE
failed to activate unexpected token

### ISSUE THREAD

**Issue by Xendergo** [pusher/atom-pair#128] opened 2017-08-10 18:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package 2.0.12

### Stack Trace

Failed to activate the atom-pair package

```
At Unexpected token )

SyntaxError: Unexpected token )
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-pair/lib/atom_pair.coffee:42:15)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-git-revert 0.2.5 
atom-pair 2.0.12 
atom-save-all 0.4.1 
```

**Comment by oumad** [comment] 2017-08-10 20:54
A colleague of mine had this exact issue on his computer today, It has to do with the atom version, we fixed it by going back to 1.18.0 version of atom

**Comment by 6temes** [comment] 2017-08-17 07:06
Duplicated #126

**Comment by 6temes** [comment] 2017-08-17 07:09
Duplicate of #126

**Closed as completed** 2017-08-30 09:55 UTC
